import { IUser, IChat, IChatMessage } from '@types/index';

export const dummyUsers: IUser[] = [
  {
    id: 'u1',
    name: 'Pritul',
    username: 'pritul_1906',
    avatar: 'https://i.pravatar.cc/150?img=1',
    status: 'online',
    statusMessage: 'Building amazing apps',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: 'u2',
    name: 'Kshiteesh Dayal',
    username: 'kshiteesh_dayal',
    avatar: 'https://i.pravatar.cc/150?img=2',
    status: 'offline',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date(),
  },
  {
    id: 'u3',
    name: 'Abhishek',
    username: 'abhishek_0109',
    avatar: 'https://i.pravatar.cc/150?img=3',
    status: 'online',
    statusMessage: 'Working on backend',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date(),
  },
  {
    id: 'u4',
    name: 'Khushi',
    username: 'khushi_coder',
    avatar: 'https://i.pravatar.cc/150?img=4',
    status: 'away',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date(),
  },
  {
    id: 'u5',
    name: 'Divya',
    username: 'divya_designer',
    avatar: 'https://i.pravatar.cc/150?img=5',
    status: 'offline',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date(),
  },
  {
    id: 'current-user',
    name: 'You',
    username: 'reely_karan',
    avatar: 'https://i.pravatar.cc/150?img=0',
    status: 'online',
    statusMessage: 'Always available',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
];

export const dummyMessages: IChatMessage[] = [
  {
    id: 'msg1',
    conversationId: '1',
    senderId: 'u1',
    sender: dummyUsers[0],
    content: 'Yaha toh eek ashish naam ke bande ko hire kar liya hai wo aab live krne reh gha hai',
    isEdited: false,
    createdAt: new Date(Date.now() - 300000),
    readBy: ['current-user'],
  },
  {
    id: 'msg2',
    conversationId: '1',
    senderId: 'current-user',
    sender: dummyUsers[5],
    content: 'Loda inka kuch hona dekhte jao ek hi din bhaanda futenga',
    isEdited: false,
    createdAt: new Date(Date.now() - 240000),
    readBy: ['u1'],
  },
  {
    id: 'msg3',
    conversationId: '1',
    senderId: 'u1',
    sender: dummyUsers[0],
    content: 'Eek backend developer chahiye shan ko le lete hai',
    isEdited: false,
    createdAt: new Date(Date.now() - 180000),
    readBy: ['current-user'],
  },
  {
    id: 'msg4',
    conversationId: '1',
    senderId: 'current-user',
    sender: dummyUsers[5],
    content: 'Acha ye mujhe bass bata do play store me app to deploy kaise krte krna hain requirements kya hai',
    isEdited: false,
    createdAt: new Date(Date.now() - 120000),
    readBy: ['u1'],
  },
  {
    id: 'msg5',
    conversationId: '1',
    senderId: 'u1',
    sender: dummyUsers[0],
    content: 'Hmm badhiya hai bass eek baar funding toh hone do',
    isEdited: false,
    createdAt: new Date(),
    readBy: ['current-user'],
  },
];

export const dummyChats: IChat[] = [
  {
    id: '1',
    participants: [dummyUsers[0]],
    lastMessage: dummyMessages[4],
    lastMessageAt: new Date(),
    isGroup: false,
    name: 'Pritul',
    avatar: dummyUsers[0].avatar,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
    unreadCount: 2,
    isPinned: false,
    isMuted: false,
  },
  {
    id: '2',
    participants: [dummyUsers[1]],
    lastMessage: {
      id: 'msg-u2-1',
      conversationId: '2',
      senderId: 'u2',
      sender: dummyUsers[1],
      content: 'You sent an attachment. · 2h',
      isEdited: false,
      createdAt: new Date(Date.now() - 7200000),
      readBy: ['current-user'],
    },
    lastMessageAt: new Date(Date.now() - 7200000),
    isGroup: false,
    name: 'Kshiteesh Dayal',
    avatar: dummyUsers[1].avatar,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date(),
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
  },
  {
    id: '3',
    participants: [dummyUsers[2], dummyUsers[3], dummyUsers[4]],
    lastMessage: {
      id: 'msg-u3-1',
      conversationId: '3',
      senderId: 'u3',
      sender: dummyUsers[2],
      content: '_abhishek_0109_ reacted 👍 to your message · 1d',
      isEdited: false,
      createdAt: new Date(Date.now() - 86400000),
      readBy: ['current-user'],
    },
    lastMessageAt: new Date(Date.now() - 86400000),
    isGroup: true,
    name: 'FOURS',
    avatar: 'https://i.pravatar.cc/150?img=10',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date(),
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
  },
  {
    id: '4',
    participants: [dummyUsers[3]],
    lastMessage: {
      id: 'msg-u4-1',
      conversationId: '4',
      senderId: 'u4',
      sender: dummyUsers[3],
      content: 'Thanku ❤️',
      isEdited: false,
      createdAt: new Date(Date.now() - 86400000),
      readBy: ['current-user'],
    },
    lastMessageAt: new Date(Date.now() - 86400000),
    isGroup: false,
    name: 'Khushi',
    avatar: dummyUsers[3].avatar,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date(),
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
  },
  {
    id: '5',
    participants: [dummyUsers[4]],
    lastMessage: {
      id: 'msg-u5-1',
      conversationId: '5',
      senderId: 'u5',
      sender: dummyUsers[4],
      content: 'You sent an attachment. · 3d',
      isEdited: false,
      createdAt: new Date(Date.now() - 259200000),
      readBy: ['current-user'],
    },
    lastMessageAt: new Date(Date.now() - 259200000),
    isGroup: false,
    name: 'Divya',
    avatar: dummyUsers[4].avatar,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date(),
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
  },
];
